--liquibase formatted sql

--changeset ddzhukashev:1
create table medication
(
    id bigint generated by default as identity
    constraint users_pkey primary key,
    cost integer,
    description varchar(255),
    medname varchar(255)
);

