eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ADDRESS:localhost:8671}/eureka

auth:
  service:
    app:
      name: "auth-service"
    context:
      path: "/api/auth"
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    topic: ${REDIS_TOPIC:default_topic}