---
spring:
  cloud:
    gcp:
      sql:
        enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost:5434}/file_service
    username: postgres
    password: postgres_password
    hikari:
      maximumPoolSize: 5
      connection-timeout: 20000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

minio:
  url: http://fileminio:9000
  bucket: my-bucket
  access:
    name: "minio_access_key"
    secret: "minio_secret_key"
