--liquibase formatted sql

--changeset ddzhukashev:1
create table clientfile
(
    id          bigint generated by default as identity
        constraint users_pkey
            primary key,
    owner       varchar,
    file_index   UUID,
    filename    varchar,
    size        bigint,
    title       varchar,
    description varchar
);

